/**
 * Created by anuradhawick on 9/11/17.
 */
import uuidv4 from 'uuid/v4';
import fs from 'fs';
import path from 'path';

import WrapBlast from '../../python-wrappers/blast/wrap-blast';


export default class Blast {

    static data = [ { title: 'gi|1219041180|ref|XM_021875076.1| PREDICTED: Chenopodium quinoa cold-regulated 413 plasma membrane protein 2-like (LOC110697660), mRNA',
            length: 1173,
            e: 1.0278e-117,
            query: 'ACAGAAAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTC...',
            match: '|| ||||||||| |||| | |||| ||  |||| |||| | |||| ||| | |||| ||| ||| ||||| | ||...',
            subject: 'ACCGAAAATGGGCAGAGGAGTGAATTATATGGCAATGACACCTGAGCAACTAGCCGCGGCCAATTTGATCAACTC...' },
            { title: 'gi|1226796956|ref|XM_021992092.1| PREDICTED: Spinacia oleracea cold-regulated 413 plasma membrane protein 2-like (LOC110787470), mRNA',
                length: 672,
                e: 6.48615e-114,
                query: 'AAAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGAT...',
                match: '|||||||| |||  |||| | || ||||| |||||||| || ||||| |||| ||| ||| ||||||||||||||...',
                subject: 'AAAATGGGTAGACGAATGGATTATTTGGCGATGAAAACCGAGCAATTAGCCGCGGCCAATTTGATCGATTCCGAT...' },
            { title: 'gi|731339628|ref|XM_010682658.1| PREDICTED: Beta vulgaris subsp. vulgaris cold-regulated 413 plasma membrane protein 2 (LOC104895996), mRNA',
                length: 847,
                e: 1.74048e-108,
                query: 'TTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGATATCAATGAGCTTAAAATGGCAACA...',
                match: '||||||||||||||||| ||| ||||  |||||||| |||| ||||  ||||| ||||| ||||| || ||    ...',
                subject: 'TTGGCCATGAAAACTGAGCAAATGGCGTTGGCTAATTTGATAGATTATGATATGAATGAACTTAAGATCGCTTTG...' },
            { title: 'gi|1009144954|ref|XM_016034586.1| PREDICTED: Ziziphus jujuba cold-regulated 413 plasma membrane protein 2-like (LOC107424728), mRNA',
                length: 827,
                e: 9.01589e-106,
                query: 'AAAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGAT...',
                match: '|||||||||||    ||| |||  ||||| |||| |||||||| |   |||  |||| |  ||||  |||| |||...',
                subject: 'AAAATGGGGAGG---ATGGAGTTTTTGGCTATGAGAACTGATCCA---GCCACGGCTGACTTGATAAATTCTGAT...' },
            { title: 'gi|1098839281|ref|XM_018970776.1| PREDICTED: Juglans regia cold-regulated 413 plasma membrane protein 2 (LOC108995251), mRNA',
                length: 977,
                e: 1.33808e-103,
                query: 'AATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATT---------GGCCGTGGCTAATATGATCGA...',
                match: '||||||||| |||  | | || |||||||||||||||||||             ||||  |||  || |||||||...',
                subject: 'AATGGGGAG-GAA--GGATTATTTGGCCATGAAAACTGATCCGGCCACGGCCACGGCCACGGCGGATTTGATCGA...' },
            { title: 'gi|1204884098|ref|XM_021445554.1| PREDICTED: Herrania umbratica cold-regulated 413 plasma membrane protein 2-like (LOC110429488), mRNA',
                length: 905,
                e: 1.02871e-98,
                query: 'AAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGATA...',
                match: '|||||||||||   ||| | || ||||| |||||||| ||||   | || |  |   || |||||  ||| ||||...',
                subject: 'AAATGGGGAGA---ATGGACTATTTGGCTATGAAAACAGATCCTGTAGCAGAAG---ATTTGATCAGTTCTGATA...' },
            { title: 'gi|985431980|ref|XM_006466626.2| PREDICTED: Citrus sinensis cold-regulated 413 plasma membrane protein 2 (LOC102620025), transcript variant X4, mRNA',
                length: 888,
                e: 1.02871e-98,
                query: 'AAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGATA...',
                match: '|||||||||||    |||| || ||||| |||||||||||| |   ||  |  ||  |  |||||   || ||| ...',
                subject: 'AAATGGGGAGAT---TGAATTATTTGGCTATGAAAACTGATGATCAGGTTGCAGCAGAGTTGATCAGCTCTGATT...' },
            { title: 'gi|985431979|ref|XM_006466624.2| PREDICTED: Citrus sinensis cold-regulated 413 plasma membrane protein 2 (LOC102620025), transcript variant X2, mRNA',
                length: 900,
                e: 1.02871e-98,
                query: 'AAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGATA...',
                match: '|||||||||||    |||| || ||||| |||||||||||| |   ||  |  ||  |  |||||   || ||| ...',
                subject: 'AAATGGGGAGAT---TGAATTATTTGGCTATGAAAACTGATGATCAGGTTGCAGCAGAGTTGATCAGCTCTGATT...' },
            { title: 'gi|985431978|ref|XM_006466623.2| PREDICTED: Citrus sinensis cold-regulated 413 plasma membrane protein 2 (LOC102620025), transcript variant X1, mRNA',
                length: 970,
                e: 1.02871e-98,
                query: 'AAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGATA...',
                match: '|||||||||||    |||| || ||||| |||||||||||| |   ||  |  ||  |  |||||   || ||| ...',
                subject: 'AAATGGGGAGAT---TGAATTATTTGGCTATGAAAACTGATGATCAGGTTGCAGCAGAGTTGATCAGCTCTGATT...' },
            { title: 'gi|568824605|ref|XM_006466625.1| PREDICTED: Citrus sinensis cold-regulated 413 plasma membrane protein 2 (LOC102620025), transcript variant X3, mRNA',
                length: 911,
                e: 1.02871e-98,
                query: 'AAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGATA...',
                match: '|||||||||||    |||| || ||||| |||||||||||| |   ||  |  ||  |  |||||   || ||| ...',
                subject: 'AAATGGGGAGAT---TGAATTATTTGGCTATGAAAACTGATGATCAGGTTGCAGCAGAGTTGATCAGCTCTGATT...' },
            { title: 'gi|567866318|ref|XM_006425719.1| Citrus clementina hypothetical protein (CICLE_v10026511mg) mRNA, complete cds',
                length: 1122,
                e: 1.02871e-98,
                query: 'AAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGATA...',
                match: '|||||||||||    |||| || ||||| |||||||||||| |   ||  |  ||  |  |||||   || ||| ...',
                subject: 'AAATGGGGAGAT---TGAATTATTTGGCTATGAAAACTGATGATCAGGTTGCAGCAGAGTTGATCAGCTCTGATT...' },
            { title: 'gi|567866316|ref|XM_006425718.1| Citrus clementina hypothetical protein (CICLE_v10026511mg) mRNA, complete cds',
                length: 1202,
                e: 1.02871e-98,
                query: 'AAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGATA...',
                match: '|||||||||||    |||| || ||||| |||||||||||| |   ||  |  ||  |  |||||   || ||| ...',
                subject: 'AAATGGGGAGAT---TGAATTATTTGGCTATGAAAACTGATGATCAGGTTGCAGCAGAGTTGATCAGCTCTGATT...' },
            { title: 'gi|567866314|ref|XM_006425717.1| Citrus clementina hypothetical protein (CICLE_v10026511mg) mRNA, complete cds',
                length: 971,
                e: 1.02871e-98,
                query: 'AAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGATA...',
                match: '|||||||||||    |||| || ||||| |||||||||||| |   ||  |  ||  |  |||||   || ||| ...',
                subject: 'AAATGGGGAGAT---TGAATTATTTGGCTATGAAAACTGATGATCAGGTTGCAGCAGAGTTGATCAGCTCTGATT...' },
            { title: 'gi|567866312|ref|XM_006425716.1| Citrus clementina hypothetical protein (CICLE_v10026511mg) mRNA, complete cds',
                length: 886,
                e: 1.02871e-98,
                query: 'AAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGATA...',
                match: '|||||||||||    |||| || ||||| |||||||||||| |   ||  |  ||  |  |||||   || ||| ...',
                subject: 'AAATGGGGAGAT---TGAATTATTTGGCTATGAAAACTGATGATCAGGTTGCAGCAGAGTTGATCAGCTCTGATT...' },
            { title: 'gi|1227938481|ref|XM_022049453.1| PREDICTED: Carica papaya cold-regulated 413 plasma membrane protein 2-like (LOC110820077), mRNA',
                length: 1009,
                e: 4.3742e-97,
                query: 'AGAAAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCG...',
                match: '|||||||||||||    ||| | || ||||| ||||| ||||||||   ||||   ||| || | |||  ||| |...',
                subject: 'AGAAAATGGGGAGG---ATGGAATATTTGGCTATGAAGACTGATCA---GGCCACTGCTGATCTCATCACTTCTG...' },
            { title: 'gi|1063463253|ref|XM_007047033.2| PREDICTED: Theobroma cacao cold-regulated 413 plasma membrane protein 2 (LOC18611025), transcript variant X2, mRNA',
                length: 1071,
                e: 1.85996e-95,
                query: 'TGTGAACAGA-AAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGAT...',
                match: '|| |||| || |||||||||||   ||| | || ||||| |||||||| ||||   | || |  |   || ||||...',
                subject: 'TGAGAACTGAGAAATGGGGAGA---ATGGACTATTTGGCTATGAAAACAGATCCTGTAGCAGAAG---ATTTGAT...' },
            { title: 'gi|1063463252|ref|XM_007047032.2| PREDICTED: Theobroma cacao cold-regulated 413 plasma membrane protein 2 (LOC18611025), transcript variant X1, mRNA',
                length: 1065,
                e: 1.85996e-95,
                query: 'TGTGAACAGA-AAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGAT...',
                match: '|| |||| || |||||||||||   ||| | || ||||| |||||||| ||||   | || |  |   || ||||...',
                subject: 'TGAGAACTGAGAAATGGGGAGA---ATGGACTATTTGGCTATGAAAACAGATCCTGTAGCAGAAG---ATTTGAT...' },
            { title: 'gi|1098846744|ref|XM_018974650.1| PREDICTED: Juglans regia cold-regulated 413 plasma membrane protein 2-like (LOC108998174), mRNA',
                length: 975,
                e: 9.63481e-93,
                query: 'AATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGATAT...',
                match: '|||||||||    ||||| || ||||| |||||||||||||    |||  ||| | || ||||||  || |||||...',
                subject: 'AATGGGGAGG---ATGAATTATTTGGCTATGAAAACTGATCC---GGCAATGGATGATTTGATCGGCTCTGATAT...' },
            { title: 'gi|1187397285|gb|KX009413.1| Santalum album COR413-PM2 mRNA, complete cds',
                length: 837,
                e: 3.36288e-92,
                query: 'AATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGATAT...',
                match: '|||||||||    ||| | | ||||||||||||||| ||||    |||||  |   || ||||| ||||||| ||...',
                subject: 'AATGGGGAGG---ATGGATTTCTTGGCCATGAAAACAGATCCCGCGGCCGCCG---ATTTGATCAATTCCGACAT...' },
            { title: 'gi|1079253150|ref|XM_009343631.2| PREDICTED: Pyrus x bretschneideri cold-regulated 413 plasma membrane protein 2-like (LOC103933927), mRNA',
                length: 861,
                e: 1.74201e-89,
                query: 'TGATCGATTCCGATATCAATGAGCTTAAAATGGCAACAATGAGGCTCATCAATGATGCTAGTATGCTCGGTCATT...',
                match: '|||| ||||| |||||||| ||||| || || ||| | | ||| ||||||| |||||| |  | ||| |||  ||...',
                subject: 'TGATAGATTCAGATATCAAAGAGCTCAAGATTGCAGCCAAGAGACTCATCAGTGATGCCACCAAGCTTGGTGGTT...' },
            { title: 'gi|1079253149|ref|XM_009343644.2| PREDICTED: Pyrus x bretschneideri cold-regulated 413 plasma membrane protein 2-like (LOC103933943), mRNA',
                length: 876,
                e: 1.74201e-89,
                query: 'TGATCGATTCCGATATCAATGAGCTTAAAATGGCAACAATGAGGCTCATCAATGATGCTAGTATGCTCGGTCATT...',
                match: '|||| ||||| |||||||| ||||| || || ||| | | ||| ||||||| |||||| |  | ||| |||  ||...',
                subject: 'TGATAGATTCAGATATCAAAGAGCTCAAGATTGCAGCCAAGAGACTCATCAGTGATGCCACCAAGCTTGGTGGTT...' },
            { title: 'gi|1079239703|ref|XM_009378191.2| PREDICTED: Pyrus x bretschneideri cold-regulated 413 plasma membrane protein 2 (LOC103965177), mRNA',
                length: 885,
                e: 1.74201e-89,
                query: 'TGATCGATTCCGATATCAATGAGCTTAAAATGGCAACAATGAGGCTCATCAATGATGCTAGTATGCTCGGTCATT...',
                match: '|||| ||||| |||||||| ||||| || || ||| | | ||| ||||||| |||||| |  | ||| |||  ||...',
                subject: 'TGATAGATTCAGATATCAAAGAGCTCAAGATTGCAGCCAAGAGACTCATCAGTGATGCCACCAAGCTTGGTGGTT...' },
            { title: 'gi|743838297|ref|XM_011027373.1| PREDICTED: Populus euphratica cold-regulated 413 plasma membrane protein 2 (LOC105126500), transcript variant X2, mRNA',
                length: 1132,
                e: 6.08023e-89,
                query: 'AAAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGAT...',
                match: '|||||||||||    ||| |||  |||   ||||| |||||| |    | |   |||||| | || |||||||||...',
                subject: 'AAAATGGGGAGG---ATGGAGTTTTTGAAGATGAAGACTGATGATGAAGTCAGCGCTAATTTAATTGATTCCGAT...' },
            { title: 'gi|743838293|ref|XM_011027372.1| PREDICTED: Populus euphratica cold-regulated 413 plasma membrane protein 2 (LOC105126500), transcript variant X1, mRNA',
                length: 980,
                e: 6.08023e-89,
                query: 'AAAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGAT...',
                match: '|||||||||||    ||| |||  |||   ||||| |||||| |    | |   |||||| | || |||||||||...',
                subject: 'AAAATGGGGAGG---ATGGAGTTTTTGAAGATGAAGACTGATGATGAAGTCAGCGCTAATTTAATTGATTCCGAT...' },
            { title: 'gi|1216950057|ref|XM_021815585.1| PREDICTED: Hevea brasiliensis cold-regulated 413 plasma membrane protein 2-like (LOC110658100), transcript variant X2, mRNA',
                length: 1073,
                e: 7.40723e-88,
                query: 'AAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGATA...',
                match: '||||||||||    ||| ||||||||   ||||  ||||||||| |  |   |||  || ||||| | || ||| ...',
                subject: 'AAATGGGGAGG---ATGGAGTACTTGAAAATGAGTACTGATCAAGTACC---GGCCGATTTGATCAAGTCTGATC...' },
            { title: 'gi|1216950055|ref|XM_021815584.1| PREDICTED: Hevea brasiliensis cold-regulated 413 plasma membrane protein 2-like (LOC110658100), transcript variant X1, mRNA',
                length: 1024,
                e: 7.40723e-88,
                query: 'AAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGATA...',
                match: '||||||||||    ||| ||||||||   ||||  ||||||||| |  |   |||  || ||||| | || ||| ...',
                subject: 'AAATGGGGAGG---ATGGAGTACTTGAAAATGAGTACTGATCAAGTACC---GGCCGATTTGATCAAGTCTGATC...' },
            { title: 'gi|1162571919|ref|XM_020568695.1| PREDICTED: Prunus persica cold-regulated 413 plasma membrane protein 2 (LOC18770198), transcript variant X2, mRNA',
                length: 929,
                e: 3.83704e-85,
                query: 'TGATCGATTCCGATATCAATGAGCTTAAAATGGCAACAATGAGGCTCATCAATGATGCTAGTATGCTCGGTCATT...',
                match: '||||  |||| || |||||||| || || || ||| | | ||  |||||||||||||| | || ||| |||   |...',
                subject: 'TGATAAATTCAGACATCAATGATCTCAAGATTGCAGCCAAGAAACTCATCAATGATGCCACTAAGCTTGGTGGGT...' },
            { title: 'gi|1162571918|ref|XM_007202530.2| PREDICTED: Prunus persica cold-regulated 413 plasma membrane protein 2 (LOC18770198), transcript variant X1, mRNA',
                length: 811,
                e: 3.83704e-85,
                query: 'TGATCGATTCCGATATCAATGAGCTTAAAATGGCAACAATGAGGCTCATCAATGATGCTAGTATGCTCGGTCATT...',
                match: '||||  |||| || |||||||| || || || ||| | | ||  |||||||||||||| | || ||| |||   |...',
                subject: 'TGATAAATTCAGACATCAATGATCTCAAGATTGCAGCCAAGAAACTCATCAATGATGCCACTAAGCTTGGTGGGT...' },
            { title: 'gi|1229761331|ref|XM_022277554.1| PREDICTED: Momordica charantia cold-regulated 413 plasma membrane protein 2-like (LOC111005887), mRNA',
                length: 850,
                e: 1.33926e-84,
                query: 'ATTCCGATATCAATGAGCTTAAAATGGCAACAATGAGGCTCATCAATGATGCTAGTATGCTCGGTCATTACGGGT...',
                match: '|||| |||||||| ||||||||||| ||| | | ||||||  |  |  |||| |  | |||||||    | ||  ...',
                subject: 'ATTCTGATATCAACGAGCTTAAAATTGCAGCCACGAGGCTTCTTGAACATGCCACCAAGCTCGGTGGAAAGGGCC...' },
            { title: 'gi|566180892|ref|XM_006380679.1| Populus trichocarpa cold-acclimation family protein (POPTR_0007s12060g) mRNA, complete cds',
                length: 1182,
                e: 4.67447e-84,
                query: 'AAAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGAT...',
                match: '|||||||||||    ||| |||  |||   ||||| |||||| |    | |   |||||| | || || ||||||...',
                subject: 'AAAATGGGGAGG---ATGGAGTTTTTGAAGATGAAGACTGATGATGAAGTCAGCGCTAATTTAATTGAGTCCGAT...' },
            { title: 'gi|764593175|ref|XM_004300526.2| PREDICTED: Fragaria vesca subsp. vesca cold-regulated 413 plasma membrane protein 2 (LOC101313417), mRNA',
                length: 1105,
                e: 1.63155e-83,
                query: 'ATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAAT---ATGATCGATTCCGAT...',
                match: '|||||||| |   || | || ||||| ||||||||||| | | | ||   ||| |||    ||||  ||||||||...',
                subject: 'ATGGGGAGGG---TGGACTATTTGGCTATGAAAACTGACCCAGTTGC---GGCCAATGAGTTGATGAATTCCGAT...' },
            { title: 'gi|1104507484|ref|XM_002274845.4| PREDICTED: Vitis vinifera cold-regulated 413 plasma membrane protein 2 (LOC100267774), mRNA',
                length: 893,
                e: 5.69468e-83,
                query: 'TGAACAGAAAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGA...',
                match: '||||  ||||||||||||    ||| ||||  |||| |||||||||||||    |  |    | ||| ||||  |...',
                subject: 'TGAAACGAAAATGGGGAGG---ATGGAGTATCTGGCTATGAAAACTGATCCC--GAACCAACCCAAT-TGATTAA...' },
            { title: 'gi|349709091|emb|FQ378501.1| Vitis vinifera clone SS0AEB13YG07',
                length: 834,
                e: 5.69468e-83,
                query: 'TGAACAGAAAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGA...',
                match: '||||  ||||||||||||    ||| ||||  |||| |||||||||||||    |  |    | ||| ||||  |...',
                subject: 'TGAAACGAAAATGGGGAGG---ATGGAGTATCTGGCTATGAAAACTGATCCC--GAACCAACCCAAT-TGATTAA...' },
            { title: 'gi|1220094463|ref|XM_021978417.1| PREDICTED: Prunus avium cold-regulated 413 plasma membrane protein 2-like (LOC110773902), mRNA',
                length: 896,
                e: 1.98764e-82,
                query: 'TGATCGATTCCGATATCAATGAGCTTAAAATGGCAACAATGAGGCTCATCAATGATGCTAGTATGCTCGGTCATT...',
                match: '||||  |||| || |||||||| || || || ||| | | ||  |||||||| ||||| | || ||| |||   |...',
                subject: 'TGATAAATTCAGACATCAATGATCTCAAGATTGCAGCCAAGAAACTCATCAAAGATGCCACTAAGCTTGGTGGGT...' },
            { title: 'gi|1220047144|ref|XM_021953815.1| PREDICTED: Prunus avium cold-regulated 413 plasma membrane protein 2-like (LOC110753022), mRNA',
                length: 894,
                e: 1.98764e-82,
                query: 'TGATCGATTCCGATATCAATGAGCTTAAAATGGCAACAATGAGGCTCATCAATGATGCTAGTATGCTCGGTCATT...',
                match: '||||  |||| || |||||||| || || || ||| | | ||  |||||||| ||||| | || ||| |||   |...',
                subject: 'TGATAAATTCAGACATCAATGATCTCAAGATTGCAGCCAAGAAACTCATCAAAGATGCCACTAAGCTTGGTGGGT...' },
            { title: 'gi|1216289774|ref|XM_021774063.1| PREDICTED: Manihot esculenta cold-regulated 413 plasma membrane protein 2-like (LOC110627712), mRNA',
                length: 988,
                e: 1.98764e-82,
                query: 'GAAAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATT---GGCCGTGGCTAATATGATCGATTC...',
                match: '||||||||||||    ||  ||||||||   ||||  ||||||||| |   |||||      || ||||  | ||...',
                subject: 'GAAAATGGGGAGG---ATTGAGTACTTGAAAATGAGTACTGATCAAGTAAAGGCCG------ATTTGATTCAATC...' },
            { title: 'gi|1102738967|ref|XM_010256725.2| PREDICTED: Nelumbo nucifera cold-regulated 413 plasma membrane protein 2 (LOC104595819), mRNA',
                length: 901,
                e: 6.93753e-82,
                query: 'AAAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGAT...',
                match: '|||||||||||    ||  ||||  ||||||||||||||||||   || |    |   |  ||||   |||||| ...',
                subject: 'AAAATGGGGAGG---ATTCAGTATCTGGCCATGAAAACTGATCCGATGACAACCG---AGTTGATTAGTTCCGAC...' },
            { title: 'gi|1216294338|ref|XM_021776478.1| PREDICTED: Manihot esculenta cold-regulated 413 plasma membrane protein 2-like (LOC110629490), mRNA',
                length: 920,
                e: 3.59373e-79,
                query: 'AGTACTTGGCCATGAAAACTGATCAATTG---GCCGTGGCTAATATGATCGATTCCGATATCAATGAGCTTAAAA...',
                match: '||||||||   ||||  ||||||||| |    ||||      || |||||   || ||| |||||||||| ||  ...',
                subject: 'AGTACTTGAAAATGAGTACTGATCAAGTAAAAGCCG------ATTTGATCCGGTCTGATCTCAATGAGCTCAAGG...' },
            { title: 'gi|1027112245|ref|XM_008243375.2| PREDICTED: Prunus mume cold-regulated 413 plasma membrane protein 2-like (LOC103340011), mRNA',
                length: 932,
                e: 1.25434e-78,
                query: 'TGATCGATTCCGATATCAATGAGCTTAAAATGGCAACAATGAGGCTCATCAATGATGCTAGTATGCTCGGTCATT...',
                match: '||||  |||| || |||||||| || || || ||| | | ||  |||||||| ||||| | || ||| |||   |...',
                subject: 'TGATAAATTCAGACATCAATGATCTCAAGATTGCAGCCAAGAAACTCATCAAAGATGCCACTAAGCTTGGTGGGT...' },
            { title: 'gi|848856318|ref|XM_013000712.1| PREDICTED: Erythranthe guttatus cold-regulated 413 plasma membrane protein 2 (LOC105975512), mRNA',
                length: 923,
                e: 4.37806e-78,
                query: 'AAAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGAT...',
                match: '||||||||||||   ||  | ||||| || |||||||| ||||||    | | |||     || |||||||||| ...',
                subject: 'AAAATGGGGAGA---ATTGATTACTTAGCGATGAAAACCGATCAAGAAACGGCGGCGT---TGCTCGATTCCGAC...' },
            { title: 'gi|1216963201|ref|XM_021822463.1| PREDICTED: Hevea brasiliensis cold-regulated 413 plasma membrane protein 2-like (LOC110663212), transcript variant X1, mRNA',
                length: 1307,
                e: 1.52809e-77,
                query: 'ATATGATCGATTCCGATATCAATGAGCTTAAAATGGCAACAATGAGGCTCATCAATGATGCTAGTATGCTCGGTC...',
                match: '|| ||||  | || ||| |||||||||| ||  | ||  | | | | ||| | |||||||| | || ||| ||| ...',
                subject: 'ATTTGATTCAGTCTGATCTCAATGAGCTCAACGTTGCTGCCAAGCGACTCCTAAATGATGCCACTAGGCTTGGTG...' },
            { title: 'gi|1039849994|ref|XM_008339966.2| PREDICTED: Malus x domestica cold-regulated 413 plasma membrane protein 2 (LOC103401258), mRNA',
                length: 1055,
                e: 6.49762e-76,
                query: 'TGATCGATTCCGATATCAATGAGCTTAAAATGGCAACAATGAGGCTCATCAATGATGCTAGTATGCTCGGTCATT...',
                match: '|||| ||||| |||||||| ||||| || || ||| | | ||| ||||||| |||||| |  |  || |||  ||...',
                subject: 'TGATAGATTCAGATATCAAAGAGCTCAAGATTGCAGCCAAGAGACTCATCAGTGATGCCACCAARCTTGGTGGTT...' },
            { title: 'gi|1029070544|ref|XM_016840023.1| PREDICTED: Gossypium hirsutum cold-regulated 413 plasma membrane protein 2-like (LOC107911998), mRNA',
                length: 1063,
                e: 6.49762e-76,
                query: 'AAATGGGGAGAGAAATGA-AGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCT-AATA--TGATCGATTCC...',
                match: '||||||||||| |   || |||| ||||| |||||||| ||||      | || ||| || |  |||||  ||||...',
                subject: 'AAATGGGGAGA-ATGCGACAGTATTTGGCAATGAAAACGGATC------CTGTTGCTCAAGAATTGATCAGTTCC...' },
            { title: 'gi|1173834760|ref|XM_012223735.2| PREDICTED: Jatropha curcas cold-regulated 413 plasma membrane protein 2 (LOC105639621), transcript variant X2, mRNA',
                length: 956,
                e: 2.26789e-75,
                query: 'AAAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGAT...',
                match: '||||||||||||   ||| | ||||||   ||||  |||||| |  |    |  | | || ||||| | || |||...',
                subject: 'AAAATGGGGAGA---ATGGATTACTTGAAAATGAGTACTGATGATGTAAAAGCTGATGATTTGATCCAGTCTGAT...' },
            { title: 'gi|1173834759|ref|XM_012223734.2| PREDICTED: Jatropha curcas cold-regulated 413 plasma membrane protein 2 (LOC105639621), transcript variant X1, mRNA',
                length: 892,
                e: 2.26789e-75,
                query: 'AAAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGAT...',
                match: '||||||||||||   ||| | ||||||   ||||  |||||| |  |    |  | | || ||||| | || |||...',
                subject: 'AAAATGGGGAGA---ATGGATTACTTGAAAATGAGTACTGATGATGTAAAAGCTGATGATTTGATCCAGTCTGAT...' },
            { title: 'gi|1050628454|ref|XM_017781654.1| PREDICTED: Gossypium arboreum cold-regulated 413 plasma membrane protein 2-like (LOC108479195), transcript variant X2, mRNA',
                length: 1087,
                e: 7.91572e-75,
                query: 'AAATGGGGAGAGAAATGA-AGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCT-AATA--TGATCGATTCC...',
                match: '||||||||||| |   || |||| ||||| |||||||| ||||      | || ||| || |  |||||  ||||...',
                subject: 'AAATGGGGAGA-ATGCGACAGTATTTGGCAATGAAAACGGATC------CTGTTGCTCAAGAATTGATCAGTTCC...' },
            { title: 'gi|1050628452|ref|XM_017781653.1| PREDICTED: Gossypium arboreum cold-regulated 413 plasma membrane protein 2-like (LOC108479195), transcript variant X1, mRNA',
                length: 1087,
                e: 7.91572e-75,
                query: 'AAATGGGGAGAGAAATGA-AGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCT-AATA--TGATCGATTCC...',
                match: '||||||||||| |   || |||| ||||| |||||||| ||||      | || ||| || |  |||||  ||||...',
                subject: 'AAATGGGGAGA-ATGCGACAGTATTTGGCAATGAAAACGGATC------CTGTTGCTCAAGAATTGATCAGTTCC...' },
            { title: 'gi|823184330|ref|XM_012633708.1| PREDICTED: Gossypium raimondii cold-regulated 413 plasma membrane protein 2-like (LOC105802207), mRNA',
                length: 1068,
                e: 7.91572e-75,
                query: 'AAATGGGGAGAGAAATGA-AGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCT-AATA--TGATCGATTCC...',
                match: '||||||||||| |   || |||| ||||| |||||||| ||||      | || ||| || |  |||||  ||||...',
                subject: 'AAATGGGGAGA-ATGCGACAGTATTTGGCAATGAAAACGGATC------CTGTTGCTCAAGAATTGATCAGTTCC...' },
            { title: 'gi|1040862414|ref|XM_017386231.1| PREDICTED: Daucus carota subsp. sativus cold-regulated 413 plasma membrane protein 2 (LOC108214299), mRNA',
                length: 901,
                e: 1.1748e-72,
                query: 'TTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGATATCAATGAGCTTAAAATGGCAACA...',
                match: '||||| ||||||||||||||  ||  |  ||  | ||| |   |||| || || |||||||||||||||||  | ...',
                subject: 'TTGGCGATGAAAACTGATCATGTGAGCCAGGACATTATAA---ATTCAGACATGAATGAGCTTAAAATGGCTGCC...' },
            { title: 'gi|971545995|ref|XM_006344753.2| PREDICTED: Solanum tuberosum cold-regulated 413 plasma membrane protein 2-like (LOC102596410), mRNA',
                length: 1167,
                e: 6.0856e-70,
                query: 'AAAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGCTAATATGATCGATTCCGAT...',
                match: '|||||||||||    ||| | || ||||| ||||| |||||| ||    |  |  | ||| |||| |||   |||...',
                subject: 'AAAATGGGGAGG---ATGGATTATTTGGCTATGAAGACTGATGAAGATAC--TAACAAAT-TGATTGATGAAGAT...' } ]
    ;

    static execute(taskParams) {
        const tempPath = path.join(__dirname,uuidv4());

        // fs.writeFileSync(tempPath, taskParams);

        // const wrap = new WrapBlast(tempPath);
        //
        // return wrap.exec();

        return new Promise(resolve => resolve(Blast.data))
    }
}